#!/usr/bin/env bash
cd /tmp
wget https://github.com/sivel/speedtest-cli/archive/master.zip
unzip master.zip
cd speedtest-cli-master
chmod 755 speedtest.py
sudo mv speedtest.py /usr/local/bin/speedtest