#!/bin/bash
###########################################################################
# Speedmob Web Service
# Author: Kyle Taylor, 2018
# License: GPL (>= 2.1) [http://www.gnu.org/licenses/gpl.html]
###########################################################################

source $PWD/speedmob_results

curl -k -X POST -H "Content-Type: application/json" -d "${SM_JSON_STRING}" https://speed.kyletaylored.com/log
logger -s "Submitted speedtest results. ${SM_JSON_STRING}"
