#!/usr/bin/env bash
###########################################################################
# Originally written by: Henrik Bengtsson, 2014
# https://github.com/HenrikBengtsson/speedtest-cli-extras
# Modified to use IFTTT by: Alasdair Allan, 2015
# https://gist.github.com/aallan/bafc70a347f3b9526d30
# Modified to use .config file: Stefan Natter, 2017
# License: GPL (>= 2.1) [http://www.gnu.org/licenses/gpl.html]
###########################################################################

# import config
source $PWD/speedtest.cfg
secret_key=$ifttt_secretKey
event_name=$ifttt_event

echo "Running speed test..."

# Character for separating values
# (commas are not safe, because some servers return speeds with commas)
sep=";"
log=$PWD/ifttt.csv

# Local functions
function str_extract() {
 pattern=$1
 # Extract
 res=`grep "$pattern" $log | sed "s/$pattern//g"`
 # Drop trailing ...
 res=`echo $res | sed 's/[.][.][.]//g'`
 # Trim
 res=`echo $res | sed 's/^ *//g' | sed 's/ *$//g'`
 echo $res
}

# Display header?
if test "$1" = "--header"; then
  start="start"
  stop="stop"
  from="from"
  from_ip="from_ip"
  server="server"
  server_dist="server_dist"
  server_ping="server_ping"
  download="download"
  upload="upload"
  share_url="share_url"
else
  mkdir -p `dirname $log`

  start=`date +"%Y-%m-%d %H:%M:%S"`

  if test -n "$SPEEDTEST_CSV_SKIP" && test -f "$log"; then
    # Reuse existing results (useful for debugging)
    1>&2 echo "** Reusing existing results: $log"
  else
    # Query Speedtest
    $PWD/speedtest_cli/speedtest.py --share --server 2409 > $log
  fi

  stop=`date +"%Y-%m-%d %H:%M:%S"`

  # Parse
  from=`str_extract "Testing from "`
  from_ip=`echo $from | sed 's/.*(//g' | sed 's/).*//g'`
  from=`echo $from | sed 's/ (.*//g'`

  server=`str_extract "Hosted by "`
  server_ping=`echo $server | sed 's/.*: //g'`
  server=`echo $server | sed 's/: .*//g'`
  server_dist=`echo $server | sed 's/.*\\[//g' | sed 's/\\].*//g'`
  server=`echo $server | sed 's/ \\[.*//g'`

  download=`str_extract "Download: "`
  upload=`str_extract "Upload: "`
  share_url=`str_extract "Share results: "`
fi

# Standardize units?
if test "$1" = "--standardize"; then
  download=`echo $download | sed 's/Mbits/Mbit/'`
  upload=`echo $upload | sed 's/Mbits/Mbit/'`
fi

# Send to IFTTT
ping=`echo $server_ping | cut -d" " -f1`
dl=`echo $download | cut -d" " -f1`
ul=`echo $upload | cut -d" " -f1`
server=`echo ${server//,}`
datetime=`echo $(date +%Y/%m/%d-%H:%M:%S)`
netinfc=`echo $(ip addr | awk '/state UP/' | awk 'NR==1 {print $2}' | sed 's/.$//')`

# Get IP info
ipinfo=$(curl -sS http://ipinfo.io/${from_ip}/json | jq --raw-output '.loc')
loc=$(ipinfo | jq --raw-output '.loc')
postal=$(ipinfo | jq --raw-output '.postal')

# Store into JSON
json="{\"value1\":\"${from},${from_ip},${server},${ping},${dl},${ul},${share_url},${datetime},${netinfc},${loc},${postal}\"}"

curl -X POST -H "Content-Type: application/json" -d "${json}" https://maker.ifttt.com/trigger/${event_name}/with/key/${secret_key}

echo ""
echo ${json}
