#!/bin/bash

# Import variables
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
OS=`echo $(uname)`

# Run test every 30 minutes.
case $OS in
	Darwin)
		echo "Installing LaunchDaemon..."
		chmod +x $DIR/install_osx
		bash $DIR/install_osx
	    ;;
	Linux)
		echo "Installing crontab task..."
		echo "*/30 * * * * ${USER} speedmob --web" | crontab
	    ;;
	*) echo "System not supported."
	   exit 1
	   ;;
esac
