#!/bin/bash

# Import variables
OS=`echo $(uname)`

# Run test every 30 minutes.
case $OS in
	Darwin)
		echo "Installing LaunchDaemon..."
		chmod +x install_osx
		./install_osx
	    ;;
	Linux)
		echo "Installing crontab task..."
		echo "*/30 * * * * ${USER} speedmob --web" | crontab
	    ;;
	*) echo "System not supported."
	   exit 1
	   ;;
esac
